"""Mean-zero unit-energy probe orbits generated by fixed toral dynamics."""

from __future__ import annotations

import math

import numpy as np

from .torus import CAT_MAP, SHEAR_MAP, cat_eigensystem, integer_matrix_power, torus_grid, torus_map


METHODS = ("E1_0_isotropic", "E1_1_static_anisotropic", "E1_2_shear_koopman", "E1_3_cat_koopman")


def normalize_probe(value: np.ndarray) -> np.ndarray:
    result = np.asarray(value, dtype=np.float64)
    result = result - result.mean()
    norm = np.linalg.norm(result)
    if norm <= 1e-12:
        raise ValueError("probe has zero centered energy")
    return result / norm


def wrapped_gaussian(points: np.ndarray, sigma: float = 0.085) -> np.ndarray:
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    points = np.asarray(points, dtype=np.float64)
    return np.exp(-0.5 * np.sum(points**2, axis=-1) / sigma**2)


def seed_probe(size: int = 65, sigma: float = 0.085) -> np.ndarray:
    return normalize_probe(wrapped_gaussian(torus_grid(size), sigma))


def _reference_angle(method: str) -> float:
    if method == "E1_3_cat_koopman":
        _values, unstable, _stable, _vectors = cat_eigensystem()
        return math.atan2(float(unstable[1]), float(unstable[0]))
    return 0.0


def _chart_coordinates(size: int, orientation: float, reference_angle: float) -> np.ndarray:
    points = torus_grid(size)
    delta = float(orientation) - float(reference_angle)
    cosine, sine = math.cos(delta), math.sin(delta)
    # Image coordinates -> canonical coordinates.
    inverse_rotation = np.asarray([[cosine, sine], [-sine, cosine]], dtype=np.float64)
    return points @ inverse_rotation.T


def _static_isotropic(coords: np.ndarray, lag: int, K: int, sigma: float) -> np.ndarray:
    local_sigma = sigma * (1.0 + 0.18 * abs(lag) / max(K, 1))
    return wrapped_gaussian(coords, local_sigma)


def _static_anisotropic(coords: np.ndarray, lag: int, K: int, sigma: float) -> np.ndarray:
    rho = (3.0 + math.sqrt(5.0)) / 2.0
    magnitude = rho ** (abs(lag) / max(K, 1))
    sigma_u, sigma_s = sigma * magnitude, sigma / magnitude
    if lag < 0:
        sigma_u, sigma_s = sigma_s, sigma_u
    return np.exp(-0.5 * ((coords[..., 0] / sigma_u) ** 2 + (coords[..., 1] / sigma_s) ** 2))


def generated_kernel_bank(
    method: str,
    *,
    orientation: float,
    size: int = 65,
    K: int = 3,
    sigma: float = 0.085,
) -> np.ndarray:
    """Return (2K+1)xHxW normalized kernels without learned parameters."""
    if method not in METHODS:
        raise ValueError(f"unknown E1 method: {method}")
    if K < 1:
        raise ValueError("K must be positive")
    coords = _chart_coordinates(size, orientation, _reference_angle(method))
    kernels = []
    for lag in range(-K, K + 1):
        if method == "E1_0_isotropic":
            value = _static_isotropic(coords, lag, K, sigma)
        elif method == "E1_1_static_anisotropic":
            value = _static_anisotropic(coords, lag, K, sigma)
        else:
            matrix = SHEAR_MAP if method == "E1_2_shear_koopman" else CAT_MAP
            transformed = torus_map(coords, matrix, power=-lag)
            value = wrapped_gaussian(transformed, sigma)
        kernels.append(normalize_probe(value))
    return np.stack(kernels)


def kernel_feature_vector(correlations: np.ndarray) -> np.ndarray:
    values = np.asarray(correlations, dtype=np.float64)
    if values.ndim != 1 or values.size % 2 != 1:
        raise ValueError("correlation vector must be odd-length 1D")
    K = values.size // 2
    differences = values[K + 1 :] - values[K - 1 :: -1]
    return np.concatenate((values, differences, [values.mean(), values.var()]))


def deterministic_structure_score(correlations: np.ndarray) -> float:
    """Predeclared dynamic elongation gain; no learned classifier/readout."""
    values = np.asarray(correlations, dtype=np.float64)
    K = values.size // 2
    nonzero = np.concatenate((values[:K], values[K + 1 :]))
    elongation_gain = float(np.max(np.abs(nonzero)) - abs(values[K]))
    time_asymmetry = float(np.mean(np.abs(values[K + 1 :] - values[K - 1 :: -1])))
    return elongation_gain + 0.25 * time_asymmetry + 0.10 * float(values.var())


def local_correlations(patch: np.ndarray, kernels: np.ndarray) -> np.ndarray:
    value = normalize_probe(np.asarray(patch, dtype=np.float64))
    bank = np.asarray(kernels, dtype=np.float64)
    if bank.ndim != 3 or bank.shape[1:] != value.shape:
        raise ValueError("kernel bank and patch shape mismatch")
    return np.einsum("khw,hw->k", bank, value)
